# Default values for vizzy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5
image:
  repository: scottcbishop/vizzy
  tag: v3.1.1
  pullSecret: dockerhub.com
  pullPolicy: Always

volumeMounts:
  name: visual-data

volumes:
  name: visual-data
  claimName: visual-automation-home

resources:
  limits:
    memory: 8Gi
  requests:
    memory: 8Gi

env:
  vizzyUri:
    name: VIZZY_URI
    value: vizzy.com
  railsEnv:
    name: RAILS_ENV
    value: production

service:
  type: NodePort # accessed externally
  http:
    port: 3000

nginxIngress:
  enabled: true

# Chart dependency
postgresql:
  enabled: true

secrets:
