defaults: &default
  devise:
    auth_strategy: 'LDAP'
    ldap_email_domain: '@workday.com'
    ldap_host: '10.140.230.35'
    ldap_port: '389'
    ldap_base: 'DC=workdayinternal,DC=com'
    ldap_email_internal_domain: '@workdayinternal.com'
    password_placeholder: "Active Directory Password"
  jira:
    create_issues: yes
  slack:
    send_messages: yes
  bamboo:
    comment_on_build: yes
  jenkins:
    update_description: yes

development:
  <<: *default

test:
  <<: *default
  jira:
    create_issues: no
  slack:
    send_messages: no
  bamboo:
    comment_on_build: no
  jenkins:
    update_description: no

ci_test:
  <<: *default
  jira:
    create_issues: no
  slack:
    send_messages: no
  bamboo:
    comment_on_build: no
  jenkins:
    update_description: no

production:
  <<: *default